-- ===================================================================
-- CONVERTED SQL STATEMENTS - PostgreSQL Equivalents
-- Source: BobsBookstore .NET Application
-- Date: 2026-03-23
-- Total Application Statements: 5
-- Total Database Script Statements: 11
-- Grand Total: 16
-- ===================================================================
-- DMS Tool Attempted: YES (all 16 statements)
-- DMS Tool Result: ALL FAILED - Metadata model creation failed
-- DMS Error: "Metadata model creation failed: {'default_error_details':
--   {'message': 'No objects were found according to the specified
--   selection rules. Please review your selection rules and try again.'}}"
-- Conversion Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
-- ===================================================================

-- ===================================================================
-- SECTION 1: APPLICATION CODE SQL STATEMENTS (5)
-- ===================================================================

-- Statement 1: AuthorsController.cs - EditUsingStoredProcedure method
-- Original: DECLARE @rowsAffected INT;EXEC @rowsAffected = [dbo].[uspUpdateAuthorPersonalInfo] @BusinessEntityID, @NationalIDNumber, @BirthDate, @MaritalStatus, @Gender;SELECT @rowsAffected;
-- Conversion: DECLARE/EXEC pattern converted to CALL syntax with lowercase schema names
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
CALL bobsbookstore_dbo.uspupdateauthorpersonalinfo(@BusinessEntityID, @NationalIDNumber, @BirthDate, @MaritalStatus, @Gender);

-- Statement 2: AuthorsController.cs - FindAllAuthorsEmbeddedSql method
-- Original: SELECT * FROM bobsbookstore_dbo.author
-- Conversion: Already PostgreSQL-compatible, lowercase schema/table names maintained
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
SELECT * FROM bobsbookstore_dbo.author;

-- Statement 3: AuthorsController.cs - DeleteAuthorEmbeddedSql method
-- Original: DECLARE @rowsAffected INT;EXEC @rowsAffected = [dbo].[uspDeleteAuthor] @BusinessEntityID;SELECT @rowsAffected;
-- Conversion: DECLARE/EXEC pattern converted to CALL syntax with lowercase schema names
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
CALL bobsbookstore_dbo.uspdeleteauthor(@BusinessEntityID);

-- Statement 4: AuthorsController.cs - SelectAuthorsByHireYear method
-- Original: SELECT BusinessEntityID, TO_CHAR(ModifiedDate, 'YYYY-MM-DD HH24:MI:SS') AS FormattedModifiedDate, EXTRACT(YEAR FROM AGE(CURRENT_DATE, BirthDate))::INTEGER AS Age FROM bobsbookstore_dbo.author WHERE EXTRACT(YEAR FROM HireDate) = @HireDate;
-- Conversion: Column names converted to lowercase for PostgreSQL compatibility
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
SELECT businessentityid, TO_CHAR(modifieddate, 'YYYY-MM-DD HH24:MI:SS') AS formattedmodifieddate, EXTRACT(YEAR FROM AGE(CURRENT_DATE, birthdate))::INTEGER AS age FROM bobsbookstore_dbo.author WHERE EXTRACT(YEAR FROM hiredate) = @HireDate;

-- Statement 5: ProductsController.cs - FindAllProducts method
-- Original: EXEC [dbo].[uspGetProductData];
-- Conversion: EXEC pattern converted to SELECT FROM function call with lowercase schema names
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
SELECT * FROM bobsbookstore_dbo.uspgetproductdata();

-- ===================================================================
-- SECTION 2: DATABASE SCRIPT SQL STATEMENTS (11)
-- ===================================================================

-- Statement 6: db/adven.sql - CREATE TABLE Author
-- Original: CREATE TABLE [dbo].[Author]([BusinessEntityID] INT IDENTITY(1, 1) NOT NULL, ...)
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
CREATE TABLE bobsbookstore_dbo.author(businessentityid INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, nationalidnumber varchar(15) NOT NULL, loginid varchar(256) NOT NULL, jobtitle varchar(50) NOT NULL, birthdate date NOT NULL, maritalstatus char(1) NOT NULL, gender char(1) NOT NULL, hiredate date NOT NULL, vacationhours smallint NOT NULL DEFAULT ((0)), modifieddate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP);

-- Statement 7: db/adven.sql - CREATE TABLE Product
-- Original: CREATE TABLE [dbo].[Product]([ProductID] int IDENTITY(1, 1) NOT NULL, ...)
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
CREATE TABLE bobsbookstore_dbo.product(productid int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, name varchar(100) NOT NULL, productnumber varchar(25) NOT NULL, safetystocklevel smallint NOT NULL, standardcost numeric(19,4) NOT NULL, listprice numeric(19,4) NOT NULL);

-- Statement 8: db/adven.sql - CREATE PROCEDURE uspUpdateAuthorPersonalInfo
-- Original: CREATE PROCEDURE [dbo].[uspUpdateAuthorPersonalInfo] ...
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
CREATE OR REPLACE PROCEDURE bobsbookstore_dbo.uspupdateauthorpersonalinfo(p_businessentityid int, p_nationalidnumber varchar(15), p_birthdate timestamp, p_maritalstatus char(1), p_gender char(1)) LANGUAGE plpgsql AS $$ BEGIN UPDATE bobsbookstore_dbo.author SET nationalidnumber = p_nationalidnumber, birthdate = p_birthdate, maritalstatus = p_maritalstatus, gender = p_gender WHERE businessentityid = p_businessentityid; END; $$;

-- Statement 9: db/adven.sql - CREATE PROCEDURE uspDeleteAuthor
-- Original: CREATE PROCEDURE [dbo].[uspDeleteAuthor] ...
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
CREATE OR REPLACE PROCEDURE bobsbookstore_dbo.uspdeleteauthor(p_businessentityid int) LANGUAGE plpgsql AS $$ BEGIN DELETE FROM bobsbookstore_dbo.author WHERE businessentityid = p_businessentityid; IF NOT FOUND THEN RAISE EXCEPTION 'No author found'; END IF; END; $$;

-- Statement 10: db/adven.sql - CREATE PROCEDURE uspGetProductData (converted to FUNCTION)
-- Original: CREATE PROCEDURE [dbo].[uspGetProductData] @my_cursor CURSOR VARYING OUTPUT ...
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
CREATE OR REPLACE FUNCTION bobsbookstore_dbo.uspgetproductdata() RETURNS TABLE (productid int, name varchar(100), productnumber varchar(25), safetystocklevel smallint) LANGUAGE sql AS $$ SELECT productid, name, productnumber, safetystocklevel FROM bobsbookstore_dbo.product; $$;

-- Statement 11: db/adven.sql - CREATE VIEW VwTopMembers
-- Original: CREATE VIEW [dbo].[VwTopMembers] ...
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
CREATE OR REPLACE VIEW bobsbookstore_dbo.vwtopmembers AS SELECT * FROM (SELECT c.customerid, c.firstname, c.lastname, SUM(o.totalamount) AS totalspent FROM bobsbookstore_dbo.members c JOIN bobsbookstore_dbo.shopping o ON c.customerid = o.customerid GROUP BY c.customerid, c.firstname, c.lastname ORDER BY totalspent DESC) sub;

-- Statement 12: db/adven.sql - CREATE FUNCTION ufnGetAccountingEndDate
-- Original: CREATE FUNCTION [dbo].[ufnGetAccountingEndDate]() ...
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
CREATE OR REPLACE FUNCTION bobsbookstore_dbo.ufngetaccountingenddate() RETURNS timestamp LANGUAGE plpgsql AS $$ BEGIN RETURN (TO_TIMESTAMP('20040701', 'YYYYMMDD') + (-2) * INTERVAL '1 millisecond'); END; $$;

-- Statement 13: db/adven.sql - CREATE PROCEDURE uspGetBillOfMaterials
-- Original: CREATE PROCEDURE [dbo].[uspGetBillOfMaterials] ...
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
CREATE OR REPLACE PROCEDURE bobsbookstore_dbo.uspgetbillofmaterials(p_startproductid int, p_checkdate timestamp) LANGUAGE plpgsql AS $$ BEGIN WITH bom_cte(productassemblyid, componentid, componentdesc, perassemblyqty, standardcost, listprice, bomlevel, recursionlevel) AS (SELECT b.productassemblyid, b.componentid, p.name, b.perassemblyqty, p.standardcost, p.listprice, b.bomlevel, 0 FROM bobsbookstore_dbo.billofmaterials b INNER JOIN bobsbookstore_dbo.product p ON b.componentid = p.productid WHERE b.productassemblyid = p_startproductid AND p_checkdate >= b.startdate AND p_checkdate <= COALESCE(b.enddate, p_checkdate)) SELECT b.productassemblyid, b.componentid, b.componentdesc, SUM(b.perassemblyqty) AS totalquantity, b.standardcost, b.listprice, b.bomlevel, b.recursionlevel FROM bom_cte b GROUP BY b.componentid, b.componentdesc, b.productassemblyid, b.bomlevel, b.recursionlevel, b.standardcost, b.listprice ORDER BY b.bomlevel, b.productassemblyid, b.componentid; END; $$;

-- Statement 14: db/adven-data.sql - INSERT INTO Author (sample row)
-- Original: INSERT INTO [dbo].[Author] (...) VALUES (N'295847284', ...)
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
INSERT INTO bobsbookstore_dbo.author (nationalidnumber, loginid, organizationnode, jobtitle, birthdate, maritalstatus, gender, hiredate, vacationhours, currentflag, modifieddate) VALUES ('295847284', 'adventure-works\ken0', NULL, 'Chief Executive Officer', '1969-01-29', 'S', 'M', '2009-01-14', 99, 1, '2014-06-30');

-- Statement 15: db/bobsusedbooks.sql - Full database script conversion
-- Original: Full SQL Server database script with CREATE DATABASE, ALTER DATABASE, CREATE TABLE, INSERT, stored procedures
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
-- Note: Converted with lowercase schema (bobsbookstore_dbo), PostgreSQL data types, removed GO/USE statements, converted IDENTITY to GENERATED BY DEFAULT AS IDENTITY
-- (Full conversion already applied in db/bobsusedbooks.sql file)

-- Statement 16: db/adven-data.sql - All INSERT data statements
-- Original: INSERT data statements for Author, Person, BillOfMaterials, Product, Members, Shopping, Coupons, ProductSaleRegions, ProductSales
-- Method: DMS_FAILURE_MANUAL_CONVERSION_WITH_LOWERCASE_SCHEMA
-- Note: Converted with lowercase schema (bobsbookstore_dbo), removed N-prefix from strings, removed GO/USE statements, lowercase identifiers
-- (Full conversion already applied in db/adven-data.sql file)
